filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
"Highlight search matches
set hlsearch
" Sets <Ctrl-l> to redraw the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>
" Remaps the search and highlight so that it doesn't jump to first occurance
nnoremap * *``
" Define Indent Guide (plugin) stuff 
colorscheme default
"Change highlight color (search highlight)
hi Search cterm=NONE ctermfg=grey ctermbg=1
"Add line numbers
set number
"Add status line
set laststatus=2
set statusline="%f%m%r%h%w [%Y] [0x%02.2B]%< %F%=%4v,%4l %3p%% of %L"

set tags=./tags;/
" Enable Mouse
"set mouse=a
